In [1]:
# pull in historical data by zip

In [36]:
# Import dependencies
import pandas as pd
import numpy as np

# File to load
hot_market_file = 'RDC_MarketHotness_Monthly_Zip.csv'

In [37]:
# Read file and store as a dataframe
hot_market_df = pd.read_csv(hot_market_file)
hot_market_df.head()

,Month,ZipCode,ZipName,Nielsen HH Rank,Hotness Rank Within County,CountyFIPS,CountyName,Hotness Rank Within CBSA,CBSACode,CBSATitle,...,Views Per Property (vs US),Views Per Property (vs CBSA),Views Per Property (vs County),Median Listing Price,Median Listing Price M/M,Median Listing Price Y/Y,Median Listing Price (vs US),Median Listing Price (vs CBSA),Median Listing Price (vs County),Quality Flag
0,201904,1701,"Framingham, MA",2811,38.0,25017,Middlesex,93.0,14460,"Boston-Cambridge-Newton, MA-NH",...,1.9623,0.9398,0.9123,519500.0,-0.0378,0.0089,1.6759,0.9150,0.8031,NaN
1,201904,1005,"Barre, MA",12847,49.0,25027,Worcester,52.0,49340,"Worcester, MA-CT",...,1.2893,0.6508,0.6065,301225.0,-0.0024,0.2245,0.9717,0.9131,0.8548,NaN
2,201904,1850,"Lowell, MA",7793,8.0,25017,Middlesex,19.0,14460,"Boston-Cambridge-Newton, MA-NH",...,3.3711,1.6145,1.5673,287400.0,0.0648,0.0666,0.9271,0.5062,0.4443,NaN
3,201904,1118,"Springfield, MA",7634,1.0,25013,Hampden,2.0,44140,"Springfield, MA",...,2.1258,1.0596,0.9912,193650.0,0.0895,0.1246,0.6247,0.7450,0.8190,NaN
4,201904,1944,"Manchester, MA",12371,34.0,25009,Essex,209.0,14460,"Boston-Cambridge-Newton, MA-NH",...,1.6604,0.7952,0.6286,995900.0,-0.2623,-0.4142,3.2127,1.7540,1.8989,NaN

In [74]:
# Remove unnecessary columns
clean_hm_col_df = hot_market_df.drop(["CountyFIPS",
                                  "CountyName", 
                                  "Hotness Rank Within CBSA",
                                  "CBSACode",
                                  "CBSATitle", 
                                  "Hotness Rank ", 
                                  "Median DOM",
                                  "Median DOM M/M",
                                  "Median DOM M/M Perc",
                                  "Median DOM Y/Y",
                                  "Median DOM Y/Y Perc",
                                  "Median DOM (vs US)",
                                  "Median DOM (vs CBSA)",
                                  "Median DOM (vs County)",
                                  "Views Per Property M/M",
                                  "Views Per Property Y/Y",
                                  "Views Per Property  (vs US)",
                                  "Views Per Property  (vs CBSA)",
                                  "Views Per Property  (vs County)",
                                  "Median Listing Price",
                                  "Median Listing Price M/M",
                                  "Median Listing Price Y/Y",
                                  "Median Listing Price  (vs US)",
                                  "Median Listing Price  (vs CBSA)",
                                  "Median Listing Price  (vs County)",
                                  "Quality Flag"], axis=1)
clean_hm_col_df.head()

,Month,ZipCode,ZipName,Nielsen HH Rank,Hotness Rank Within County,Hotness Rank M/M,Hotness Rank Y/Y,Hotness Score,Supply Score,Demand Score
0,201904,1701,"Framingham, MA",2811,38.0,-351.0,-512.0,91.301322,91.231733,91.370912
1,201904,1005,"Barre, MA",12847,49.0,6093.0,-459.0,70.035427,67.438477,72.632378
2,201904,1850,"Lowell, MA",7793,8.0,2582.0,-76.0,98.383628,97.526412,99.240843
3,201904,1118,"Springfield, MA",7634,1.0,1439.0,66.0,95.154046,96.545834,93.762257
4,201904,1944,"Manchester, MA",12371,34.0,1491.0,3563.0,65.625988,45.365977,85.886000

In [84]:
clean_hm_col_df.set_index('ZipName').head()

,Month,ZipCode,Nielsen HH Rank,Hotness Rank Within County,Hotness Rank M/M,Hotness Rank Y/Y,Hotness Score,Supply Score,Demand Score
ZipName,,,,,,,,,
"Framingham, MA",201904,1701,2811,38.0,-351.0,-512.0,91.301322,91.231733,91.370912
"Barre, MA",201904,1005,12847,49.0,6093.0,-459.0,70.035427,67.438477,72.632378
"Lowell, MA",201904,1850,7793,8.0,2582.0,-76.0,98.383628,97.526412,99.240843
"Springfield, MA",201904,1118,7634,1.0,1439.0,66.0,95.154046,96.545834,93.762257
"Manchester, MA",201904,1944,12371,34.0,1491.0,3563.0,65.625988,45.365977,85.886000

In [82]:
beaverton_df = clean_hm_col_df[clean_hm_col_df.ZipName == "Beaverton, OR"]
beaverton_df.head()

,Month,ZipCode,ZipName,Nielsen HH Rank,Hotness Rank Within County,Hotness Rank M/M,Hotness Rank Y/Y,Hotness Score,Supply Score,Demand Score
4046,201904,97005,"Beaverton, OR",3970,6.0,175.0,-1289.0,73.125830,84.911748,61.339913
4681,201904,97007,"Beaverton, OR",1041,8.0,-633.0,-1763.0,68.406402,92.895553,43.917252
6548,201904,97006,"Beaverton, OR",1238,2.0,-850.0,-599.0,82.384387,97.304991,67.463782
13574,201904,97008,"Beaverton, OR",2955,1.0,372.0,-1080.0,84.943380,94.363257,75.523502

In [89]:
beaverton_sql_df = beaverton_df.rename(columns={
                                                'Nielsen HH Rank':'Nielsen_HH_Rank',
                                                'Hotness Rank Within County':'Hotness_Rank_County',
                                                'Hotness Rank M/M':'Hotness_Rank_MoM',
                                                'Hotness Rank Y/Y':'Hotness_Rank_YoY',
                                                'Hotness Score':'Hotness_Score',
                                                'Supply Score':'Supply_Score',
                                                'Demand Score':'Demand_Score'})
beaverton_sql_df.head()

,Month,ZipCode,ZipName,Nielsen_HH_Rank,Hotness_Rank_County,Hotness_Rank_MoM,Hotness_Rank_YoY,Hotness_Score,Supply_Score,Demand_Score
4046,201904,97005,"Beaverton, OR",3970,6.0,175.0,-1289.0,73.125830,84.911748,61.339913
4681,201904,97007,"Beaverton, OR",1041,8.0,-633.0,-1763.0,68.406402,92.895553,43.917252
6548,201904,97006,"Beaverton, OR",1238,2.0,-850.0,-599.0,82.384387,97.304991,67.463782
13574,201904,97008,"Beaverton, OR",2955,1.0,372.0,-1080.0,84.943380,94.363257,75.523502

In [90]:
beaverton_sql_df.to_csv("realtor_beaverton_hotmarket.csv")